const POST_MESSAGE_TYPE = {
  RUNNING: 'RUNNING',
  MESSAGE: 'MESSAGE',
  SET_CREW_MEMBERS: 'SET_CREW_MEMBERS'
} as const;

const SEND_MESSAGE_TYPE = {
  RUNNING_START: 'RUNNING_START',
  RUNNING_END: 'RUNNING_END',
  RUNNING_PAUSE: 'RUNNING_PAUSE',
  RUNNING_PREPARE: 'RUNNING_PREPARE'
} as const;

export { POST_MESSAGE_TYPE, SEND_MESSAGE_TYPE };
