enum POST_MESSAGE_TYPE {
  RUNNING = 'RUNNING',
  MESSAGE = 'MESSAGE'
}

enum SEND_MESSAGE_TYPE {
  RUNNING_START = 'RUNNING_START',
  RUNNING_END = 'RUNNING_END',
  RUNNING_PAUSE = 'RUNNING_PAUSE'
}

export { POST_MESSAGE_TYPE, SEND_MESSAGE_TYPE };
