const POST_MESSAGE_TYPE = {
  RUNNING: 'RUNNING',
  MESSAGE: 'MESSAGE'
} as const;

const SEND_MESSAGE_TYPE = {
  RUNNING_START: 'RUNNING_START',
  RUNNING_END: 'RUNNING_END',
  RUNNING_PAUSE: 'RUNNING_PAUSE'
} as const;

export { POST_MESSAGE_TYPE, SEND_MESSAGE_TYPE };
