import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Script from 'next/script';

const pretendard = localFont({
  src: '../fonts/pretendard/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const KAKAO_APP_KEY = process.env.NEXT_PUBLIC_KAKAO_MAPS_APP_KEY;
  if (!KAKAO_APP_KEY) {
    throw new Error('KAKAO_SDK_URL is not defined');
  }
  const KAKAO_SDK_URL = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${KAKAO_APP_KEY}&autoload=false`;

  return (
    <html lang="en" className={`${pretendard.variable} antialiased`}>
      <head>
        <title>Runky</title>
        <Script src={KAKAO_SDK_URL} strategy="beforeInteractive" />
      </head>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
